name: Lab4

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install modules
        run: npm i
      # - name: Running tests
      #   run: npm test
      - name: Build app
        run: npm run build

      - name: Deploy on GitHub pages
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.NAME}}
          git remote set-url origin https://${{secrets.TOKEN}}@github.com/${{secrets.NAME}}/react-pwa.git
          npm run deploy
